### PR TITLE
Fix PushByteIns

### PR DESCRIPTION
**Pull request by Aursen**

### CODE REVIEW

**Comment by ArachisH** [comment]
Screenshot_20201130-112819_Drive
It seems this instruction should only support unsigned byte values. Do you have a case where it fails to parse the instruction due to a signed byte value?

**Comment by Aursen** [comment]
Yes I had a problem when I decompiled DofusInvoker.swf. I don't have the exact error anymore since I had fixed it a long time ago.
I will try to find this error another time.

**Comment by Aursen** [comment]
image
For example with jpexs

**Comment by ArachisH** [comment]
This may have been due to a limitation with Jpexs/Java in general, as they do not support unsigned values by default. Would Flazzy crash when disassembling/deobfuscating on this instruction?

**Comment by Aursen** [comment]
Sorry for my english, it's error with value. For example:
Capture2
Capture

**Comment by Aursen** [comment]
Capture4
Capture3

**Comment by Aursen** [comment]
And when I read with Flazzy:
`		public function Test()
		{
			var test = -1;
		}`
I got pushbyte 255 with Flazzy

**Comment by ArachisH** [comment]
This is unfortunately just the way JPEXS handles signed/unsigned values. To follow the actual specification a PushByte may only contain an unsigned byte (0-255), but is then converted into a signed Int32 when pushed onto the stack. Java is not able to represent unsigned byte values out of the box, so JPEXS converts PushByte values higher than 127, and lower than 0 to PushShort or PushInt instructions. (This is why it breaks when attempting to read something like PushByte 128 since Java only has signed byte types(-128 -> 127))

If you wish to write negative or values higher than 255 then I recommend utilizing the PushInt instruction to push those values onto the stack. This will work since the AVM will coerce the PushByte value into an Int32 anyway when executing the instructions.
image

I will not accept this PR, but I really do appreciate it.

**Pull request closed without merging**
